[tool.poetry]
name = "lettpattern"
version = "0.1.0"
description = ""
authors = ["Sihan A"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
mkdocs-material = "^9.5.31"
pymdown-extensions = "^10.9"
binarytree = "^6.5.1"
matplotlib = "^3.9.2"
networkx = "^3.3"
notebook = "^7.2.1"
mkdocs-git-revision-date-localized-plugin = "^1.2.7"
sortedcontainers = "^2.4.0"
pandas = "^2.2.3"
pyarrow = "^19.0.1"
fastparquet = "^2024.11.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.8.0"
black = "^24.8.0"
flake8 = "^7.1.1"
pylint = "^3.2.6"
graphviz = "^0.20.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
