site_name: SQL 50

nav:
- Select: select.md
- Basic Joins: basic_joins.md
- Basic Aggregate Functions: basic_aggregate_functions.md
- Sorting and Grouping: sorting_and_grouping.md
- Advanced Select and Joins: advanced_select_and_joins.md
- Subqueries: subqueries.md
- Advanced String Functions Regex Clause: advanced_string_functions_regex_clause.md
