category: algorithms
dir: company
name: Company
topics:
    Amazon:
        [
            1,
            42,
            121,
            3,
            56,
            49,
            2,
            23,
            15,
            20,
            33,
            53,
            138,
            127,
            5,
            79,
            88,
            55,
            70,
            22,
            128,
            14,
            11,
            140,
            26,
            21,
            45,
            54,
            34,
            62,
        ]
    Apple:
        [
            146,
            121,
            347,
            139,
            1,
            56,
            155,
            36,
            1606,
            49,
            189,
            200,
            122,
            125,
            14,
            54,
            215,
            387,
            622,
            88,
            714,
            560,
            362,
            283,
            34,
            3,
            208,
            348,
            151,
            53,
        ]
    Bloomberg:
        [
            1,
            56,
            3,
            430,
            20,
            380,
            2,
            79,
            121,
            88,
            42,
            242,
            4,
            1169,
            31,
            5,
            394,
            78,
            146,
            14,
            128,
            34,
            217,
            22,
            560,
            21,
            2667,
            13,
            53,
            1244,
        ]
    ByteDance: [146, 2, 317, 347, 39, 424, 560, 10, 224, 56, 1171]
    Databricks: [362, 751, 348, 213, 198, 1146, 2096, 933]
    Google:
        [
            1,
            2667,
            2,
            1757,
            9,
            15,
            4,
            14,
            42,
            3,
            26,
            20,
            11,
            5,
            13,
            22,
            128,
            21,
            560,
            27,
            31,
            53,
            7,
            6,
            118,
            394,
            242,
            18,
            50,
            54,
        ]
    Meta:
        [
            215,
            162,
            199,
            88,
            1,
            50,
            125,
            71,
            56,
            129,
            138,
            146,
            121,
            23,
            31,
            34,
            76,
            133,
            65,
            20,
            19,
            14,
            207,
            2,
            3,
            173,
            26,
            4,
            15,
            9,
        ]
    Microsoft:
        [
            1,
            121,
            88,
            3,
            15,
            2,
            146,
            169,
            14,
            9,
            56,
            162,
            42,
            5,
            4,
            70,
            53,
            49,
            48,
            224,
            283,
            75,
            51,
            206,
            35,
            11,
            13,
            21,
            200,
            20,
        ]
    OpenAI: [2408, 341, 981, 2502, 735]
    PayPay: [3161, 6]
