site_name: Blind 75

nav:
- Arrays Hashing: arrays_hashing.md
- Two Pointers: two_pointers.md
- Sliding Window: sliding_window.md
- Stack: stack.md
- Binary Search: binary_search.md
- Linked List: linked_list.md
- Trees: trees.md
- Heap: heap.md
- Backtracking: backtracking.md
- Tries: tries.md
- Graphs: graphs.md
- Advanced Graphs: advanced_graphs.md
- 1D Dynamic Programming: 1d_dynamic_programming.md
- 2D Dynamic Programming: 2d_dynamic_programming.md
- Greedy: greedy.md
- Intervals: intervals.md
- Math Geometry: math_geometry.md
- Bit Manipulation: bit_manipulation.md
