site_name: Company

nav:
- Amazon: amazon.md
- Apple: apple.md
- Bloomberg: bloomberg.md
- ByteDance: bytedance.md
- Databricks: databricks.md
- Google: google.md
- Meta: meta.md
- Microsoft: microsoft.md
- OpenAI: openai.md
- PayPay: paypay.md
