name: publish

on:
    push:
        branches:
          - main

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
                fetch-depth: 0
          
          - name: Install uv
            uses: astral-sh/setup-uv@v4
            with:
                version: "latest"
          
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version-file: ".python-version"
          
          - name: Install dependencies with uv
            run: uv sync --only-group main
          
          - name: Deploy to GitHub Pages
            run: uv run mkdocs gh-deploy --force
