site_name: Premium 100

nav:
- Arrays Strings: arrays_strings.md
- Sliding Window: sliding_window.md
- Hashing: hashing.md
- Matrix: matrix.md
- Interval: interval.md
- Stack: stack.md
- Queue: queue.md
- Linked List: linked_list.md
- Binary Tree: binary_tree.md
- Binary Search Tree: binary_search_tree.md
- N-ary Tree: n-ary_tree.md
- Graph: graph.md
- Graph BFS: graph_bfs.md
- Trie: trie.md
- Heap: heap.md
- Binary Search: binary_search.md
- Design: design.md
- Backtracking: backtracking.md
- Dynamic Programming: dynamic_programming.md
- Math: math.md
